/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;

/**
 *
 * @author gabri
 */
public class JInternalFrameLogaritmica extends javax.swing.JInternalFrame{

    /**
     * Creates new form JInternalFrameLineal
     */
    private JInternalFrameImagen internal;
    private Image imagenOriginal;
    
    
    public JInternalFrameLogaritmica(JInternalFrameImagen internal, Image Oimage) {
        this.internal = internal;
        initComponents();


        this.imagenOriginal = Oimage;
        
        this.jButton1.addActionListener(new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent e) {  
                
            int valor=getjsliders1();
            BufferedImage bi = herramientas.HerramientasImagen.toBufferedImage(imagenOriginal);
            Color color;
            Color aux;
            for (int x = 0; x < bi.getWidth(); x++) {
                for (int y = 0; y < bi.getHeight(); y++) {

                    Color pixel = new Color(bi.getRGB(x, y));
                    int r = (int) ((valor * Math.log(1 + pixel.getRed())) / (Math.log(1 + valor)));
                    int g = (int) ((valor * Math.log(1 + pixel.getGreen())) / (Math.log(1 + valor)));
                    int b = (int) ((valor * Math.log(1 + pixel.getBlue())) / (Math.log(1 + valor)));

                    pixel = new Color(verificar(r), verificar(g), verificar(b));
                    bi.setRGB(x, y, pixel.getRGB());
                }
            }
            Image nueva = herramientas.HerramientasImagen.toImage(bi);              
            internal.setImagen(nueva); 

            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jSlider1.setMajorTickSpacing(10);
        jSlider1.setMaximum(255);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(17);

        jButton1.setText("Aceptar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSlider1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables

    public static int verificar(int valor) {
        if (valor > 255) {
            return 255;
        }
        if (valor < 0) {
            return 0;
        }
        return valor;
    }
    public int getjsliders1() {
                
        int umbral = this.jSlider1.getValue();
        return umbral;
    }

}
