/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;

/**
 *
 * @author carli
 */
public class JInternalFrameFiltros extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalFrameFiltros
     */
    private JInternalFrameImagen internal;

    public JInternalFrameFiltros(JInternalFrameImagen internal) {
        this.internal = internal;
        initComponents();
        this.Negativo.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                BufferedImage bi = herramientas.HerramientasImagen.toBufferedImage(internal.getImagenOriginal());
                Color color,aux;
                for(int x = 0; x< bi.getWidth(); x++){
                    for(int y = 0; y< bi.getHeight(); y++){
                        color = new Color(bi.getRGB(x, y));
                        int r = color.getRed(); // (0-255)
                        int g = color.getGreen(); // (0-255)
                        int b = color.getBlue(); // (0-255)
                        aux = new Color(255-r,255-g,255-b);
                        bi.setRGB(x, y, aux.getRGB());
                    }
                }
                Image nueva = herramientas.HerramientasImagen.toImage(bi);
                internal.setImagen(nueva);
            }

        });
        
        this.Grises.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                BufferedImage bi = herramientas.HerramientasImagen.toBufferedImage(internal.getImagenOriginal());
                Color color,aux;
                for(int x = 0; x< bi.getWidth(); x++){
                    for(int y = 0; y< bi.getHeight(); y++){
                        color = new Color(bi.getRGB(x, y));
                        int r = color.getRed(); // (0-255)
                        int g = color.getGreen(); // (0-255)
                        int b = color.getBlue(); // (0-255)
                        int media = (r+g+b)/3;
                        aux = new Color(media,media,media);
                        bi.setRGB(x, y, aux.getRGB());
                    }
                }
                Image nueva = herramientas.HerramientasImagen.toImage(bi);
                internal.setImagen(nueva);
            }
            
        });
        
        this.BW.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                BufferedImage bi = herramientas.HerramientasImagen.toBufferedImage(internal.getImagenOriginal());
                Color color,aux;
                int umbral = 382;
                for(int x = 0; x< bi.getWidth(); x++){
                    for(int y = 0; y< bi.getHeight(); y++){
                        color = new Color(bi.getRGB(x, y));
                        int r = color.getRed(); // (0-255)
                        int g = color.getGreen(); // (0-255)
                        int b = color.getBlue(); // (0-255)
                        int med = r+g+b;
                        if(med>=umbral){
                          bi.setRGB(x, y, Color.WHITE.getRGB());  
                        }else{
                           bi.setRGB(x, y, 0); 
                        }
                        aux = new Color(r,g,b);
                        
                    }
                }
                Image nueva = herramientas.HerramientasImagen.toImage(bi);
                internal.setImagen(nueva);
            }
        
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Negativo = new javax.swing.JButton();
        Grises = new javax.swing.JButton();
        BW = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        Negativo.setText("Negativos");

        Grises.setText("Escala de grises");

        BW.setText("Blanco y negro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BW, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Grises, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Negativo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Negativo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Grises, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BW, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BW;
    private javax.swing.JButton Grises;
    private javax.swing.JButton Negativo;
    // End of variables declaration//GEN-END:variables
}
