/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Filtrado.Butterworth;
import Filtrado.FiltroIdealPasaAltas;
import Filtrado.FiltroIdealPasaBajas;
import Filtrado.Gaussiano;
import herramientas.GestorGrises;
import herramientas.HerramientasImagen;
import herramientas.NumeroComplejo;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;

/**
 *
 * @author gabri
 */
public class JInternalFrameFiltrado extends javax.swing.JInternalFrame implements ActionListener {

    /**
     * Creates new form JInternalFrameConvolucion
     */
    private JInternalFrameImagen filtro;
    int size;
    Image io;
    JFramePrincipal framePrincipal;
    Butterworth B = null;
    FiltroIdealPasaAltas PA = null;
    FiltroIdealPasaBajas PB = null;
    Gaussiano G = null;
    GestorGrises g;
    NumeroComplejo[][] Filtrodecidido = null;

    public JInternalFrameFiltrado(JFramePrincipal framePrincipal, Image io, int size, GestorGrises g) {
        initComponents();
        this.framePrincipal = framePrincipal;
        this.size = size;
        this.io = io;
        this.g = g;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        VistaPrev = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        ButAlta = new javax.swing.JRadioButton();
        ButBaja = new javax.swing.JRadioButton();
        RadioSlider = new javax.swing.JSlider();
        Altas = new javax.swing.JRadioButton();
        Bajas = new javax.swing.JRadioButton();
        Gauss = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        OrdenTextF = new javax.swing.JTextField();
        Gauss1 = new javax.swing.JRadioButton();
        OkBut = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Crear Filtro");
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(250, 400));
        setPreferredSize(new java.awt.Dimension(566, 350));
        setVisible(true);

        VistaPrev.setText("Vista Previa");
        VistaPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VistaPrevActionPerformed(evt);
            }
        });

        ButAlta.setText("Butterworth(Altas)");
        ButAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAltaActionPerformed(evt);
            }
        });

        ButBaja.setText("Butterworth(Bajas)");
        ButBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButBajaActionPerformed(evt);
            }
        });

        RadioSlider.setMajorTickSpacing(20);
        RadioSlider.setMaximum(255);
        RadioSlider.setMinorTickSpacing(1);
        RadioSlider.setPaintLabels(true);
        RadioSlider.setPaintTicks(true);
        RadioSlider.setSnapToTicks(true);
        RadioSlider.setToolTipText("");
        RadioSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RadioSlider.setValueIsAdjusting(true);

        Altas.setText("Pasa Altas");
        Altas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltasActionPerformed(evt);
            }
        });

        Bajas.setText("Pasa Bajas");
        Bajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajasActionPerformed(evt);
            }
        });

        Gauss.setText("Gaussiano");
        Gauss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GaussActionPerformed(evt);
            }
        });

        jLabel1.setText("Radio");

        jLabel2.setText("Orden");

        OrdenTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdenTextFActionPerformed(evt);
            }
        });

        Gauss1.setText("Gaussiano(Inv)");
        Gauss1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gauss1ActionPerformed(evt);
            }
        });

        OkBut.setText("Ok!");
        OkBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(VistaPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OkBut, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(RadioSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Altas)
                                    .addComponent(Gauss)
                                    .addComponent(ButAlta))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Gauss1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ButBaja)
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(OrdenTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Bajas)))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButAlta)
                    .addComponent(jLabel2)
                    .addComponent(OrdenTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButBaja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Altas)
                    .addComponent(Bajas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gauss)
                    .addComponent(Gauss1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RadioSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OkBut, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VistaPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAltaActionPerformed
        this.Altas.setSelected(false);
        this.Bajas.setSelected(false);
        this.ButBaja.setSelected(false);
        this.Gauss.setSelected(false);
        this.Gauss1.setSelected(false);
        this.OrdenTextF.setEnabled(true);    }//GEN-LAST:event_ButAltaActionPerformed

    private void ButBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButBajaActionPerformed
        this.Altas.setSelected(false);
        this.Bajas.setSelected(false);
        this.ButAlta.setSelected(false);
        this.Gauss.setSelected(false);
        this.Gauss1.setSelected(false);
        this.OrdenTextF.setEnabled(true);

    }//GEN-LAST:event_ButBajaActionPerformed

    private void AltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltasActionPerformed
        this.ButBaja.setSelected(false);
        this.Bajas.setSelected(false);
        this.ButAlta.setSelected(false);
        this.Gauss.setSelected(false);
        this.Gauss1.setSelected(false);
        this.OrdenTextF.setEnabled(false);
    }//GEN-LAST:event_AltasActionPerformed

    private void BajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajasActionPerformed
        this.ButBaja.setSelected(false);
        this.Altas.setSelected(false);
        this.ButAlta.setSelected(false);
        this.Gauss.setSelected(false);
        this.Gauss1.setSelected(false);
        this.OrdenTextF.setEnabled(false);    }//GEN-LAST:event_BajasActionPerformed

    private void GaussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GaussActionPerformed
        this.ButBaja.setSelected(false);
        this.Bajas.setSelected(false);
        this.ButAlta.setSelected(false);
        this.Altas.setSelected(false);
        this.Gauss1.setSelected(false);
        this.OrdenTextF.setEnabled(false);    }//GEN-LAST:event_GaussActionPerformed

    private void OrdenTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdenTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrdenTextFActionPerformed

    private void Gauss1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gauss1ActionPerformed
        this.ButBaja.setSelected(false);
        this.Bajas.setSelected(false);
        this.ButAlta.setSelected(false);
        this.Gauss.setSelected(false);
        this.Altas.setSelected(false);
        this.OrdenTextF.setEnabled(false);    }//GEN-LAST:event_Gauss1ActionPerformed

    private void VistaPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VistaPrevActionPerformed

        if (ButAlta.isSelected()) {

            B = new Butterworth(this.RadioSlider.getValue(), new Dimension(this.size, this.size), true, Integer.parseInt(this.OrdenTextF.getText()));
            B.crearFiltro();
            this.filtro = new JInternalFrameImagen(B.getImagen());
            filtro.setVisible(true);
            framePrincipal.getjDesktopPanePrincipal().add(filtro);
            this.Filtrodecidido = B.getFiltroEspacial();
        } else if (ButBaja.isSelected()) {

            B = new Butterworth(this.RadioSlider.getValue(), new Dimension(this.size, this.size), false, Integer.parseInt(this.OrdenTextF.getText()));
            B.crearFiltro();
            this.filtro = new JInternalFrameImagen(B.getImagen());
            filtro.setVisible(true);
            framePrincipal.getjDesktopPanePrincipal().add(filtro);
            this.Filtrodecidido = B.getFiltroEspacial();
        } else if (this.Altas.isSelected()) {

            PA = new FiltroIdealPasaAltas(this.RadioSlider.getValue(), new Dimension(this.size, this.size));
            PA.crearFiltro();
            this.filtro = new JInternalFrameImagen(PA.getImagen());
            filtro.setVisible(true);
            framePrincipal.getjDesktopPanePrincipal().add(filtro);
            this.Filtrodecidido = PA.getFiltroEspacial();
        } else if (this.Bajas.isSelected()) {

            PB = new FiltroIdealPasaBajas(this.RadioSlider.getValue(), new Dimension(this.size, this.size));
            PB.crearFiltro();
            this.filtro = new JInternalFrameImagen(PB.getImagen());
            filtro.setVisible(true);
            framePrincipal.getjDesktopPanePrincipal().add(filtro);
            this.Filtrodecidido = PB.getFiltroEspacial();
        } else if (this.Gauss.isSelected()) {

            G = new Gaussiano(this.RadioSlider.getValue(), false, new Dimension(this.size, this.size));
            G.crearFiltro();
            this.filtro = new JInternalFrameImagen(G.getImagen());
            filtro.setVisible(true);
            framePrincipal.getjDesktopPanePrincipal().add(filtro);
            this.Filtrodecidido = G.getFiltroEspacial();
        } else if (this.Gauss1.isSelected()) {

            G = new Gaussiano(this.RadioSlider.getValue(), true, new Dimension(this.size, this.size));
            G.crearFiltro();
            this.filtro = new JInternalFrameImagen(G.getImagen());
            filtro.setVisible(true);
            framePrincipal.getjDesktopPanePrincipal().add(filtro);
            this.Filtrodecidido = G.getFiltroEspacial();
        }


    }//GEN-LAST:event_VistaPrevActionPerformed

    private void OkButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButActionPerformed
 if (ButAlta.isSelected()) {

            B = new Butterworth(this.RadioSlider.getValue(), new Dimension(this.size, this.size), true, Integer.parseInt(this.OrdenTextF.getText()));
            B.crearFiltro();
            this.filtro = new JInternalFrameImagen(B.getImagen());
            filtro.setVisible(true);
            framePrincipal.getjDesktopPanePrincipal().add(filtro);
            this.Filtrodecidido = B.getFiltroEspacial();
        } else if (ButBaja.isSelected()) {

            B = new Butterworth(this.RadioSlider.getValue(), new Dimension(this.size, this.size), false, Integer.parseInt(this.OrdenTextF.getText()));
            B.crearFiltro();
            this.filtro = new JInternalFrameImagen(B.getImagen());
            filtro.setVisible(true);
            framePrincipal.getjDesktopPanePrincipal().add(filtro);
            this.Filtrodecidido = B.getFiltroEspacial();
        } else if (this.Altas.isSelected()) {

            PA = new FiltroIdealPasaAltas(this.RadioSlider.getValue(), new Dimension(this.size, this.size));
            PA.crearFiltro();
            this.filtro = new JInternalFrameImagen(PA.getImagen());
            filtro.setVisible(true);
            framePrincipal.getjDesktopPanePrincipal().add(filtro);
            this.Filtrodecidido = PA.getFiltroEspacial();
        } else if (this.Bajas.isSelected()) {

            PB = new FiltroIdealPasaBajas(this.RadioSlider.getValue(), new Dimension(this.size, this.size));
            PB.crearFiltro();
            this.filtro = new JInternalFrameImagen(PB.getImagen());
            filtro.setVisible(true);
            framePrincipal.getjDesktopPanePrincipal().add(filtro);
            this.Filtrodecidido = PB.getFiltroEspacial();
        } else if (this.Gauss.isSelected()) {

            G = new Gaussiano(this.RadioSlider.getValue(), false, new Dimension(this.size, this.size));
            G.crearFiltro();
            this.filtro = new JInternalFrameImagen(G.getImagen());
            filtro.setVisible(true);
            framePrincipal.getjDesktopPanePrincipal().add(filtro);
            this.Filtrodecidido = G.getFiltroEspacial();
        } else if (this.Gauss1.isSelected()) {

            G = new Gaussiano(this.RadioSlider.getValue(), true, new Dimension(this.size, this.size));
            G.crearFiltro();
            this.filtro = new JInternalFrameImagen(G.getImagen());
            filtro.setVisible(true);
            framePrincipal.getjDesktopPanePrincipal().add(filtro);
            this.Filtrodecidido = G.getFiltroEspacial();
        }

        BufferedImage bi = HerramientasImagen.toBufferedImage(io);

        BufferedImage bnuevo = new BufferedImage(bi.getWidth(), bi.getHeight(), BufferedImage.TYPE_INT_RGB);
        g= new GestorGrises(bi);
        this.g.obtenerImagenFrecuencias(true);
        this.g.aplicarFiltro(this.Filtrodecidido);
        bnuevo = g.obtenerImagenEspacial();

        JInternalFrameImagen internalNuevo23 = new JInternalFrameImagen(bnuevo);
        internalNuevo23.setVisible(true);
        this.framePrincipal.getjDesktopPanePrincipal().add(internalNuevo23);

    }//GEN-LAST:event_OkButActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Altas;
    private javax.swing.JRadioButton Bajas;
    private javax.swing.JRadioButton ButAlta;
    private javax.swing.JRadioButton ButBaja;
    private javax.swing.JRadioButton Gauss;
    private javax.swing.JRadioButton Gauss1;
    private javax.swing.JButton OkBut;
    private javax.swing.JTextField OrdenTextF;
    private javax.swing.JSlider RadioSlider;
    private javax.swing.JButton VistaPrev;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
